name: aetos-blog

services:
  devcontainer:
    image: ghcr.io/aetos382/aetos.blog:latest
    volumes:
      - type: volume
        source: claude-code-config
        target: /home/vscode/.claude


networks:
  kroki:
  kroki-internal:
    internal: true

volumes:
  claude-code-config:
